const YtVideoData = [

    // Politics
    {
        id: 1,
        title: "Loksabha 2024 Election Result Live",
        category: "politics",
        channel: "ANI",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "2.5M",
        vidLength: "34:39",
        duration: "5 days ago"
    },
    {
        id: 2,
        title: "Political Debate on National Issues",
        category: "politics",
        channel: "NDTV",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "1.8K",
        vidLength: "01:42:15",
        duration: "2 weeks ago"
    },
    {
        id: 3,
        title: "Political Strategies for Upcoming Elections",
        category: "politics",
        channel: "BBC News",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "3.2M",
        vidLength: "50:34",
        duration: "1 month ago"
    },
    {
        id: 4,
        title: "Interview with the Prime Minister",
        category: "politics",
        channel: "CNN",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "2.9M",
        vidLength: "01:15:39",
        duration: "3 days ago"
    },
    {
        id: 5,
        title: "Political Analysis: What to Expect in 2024",
        category: "politics",
        channel: "Fox News",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "4.0K",
        vidLength: "37:45",
        duration: "1 week ago"
    },
    {
        id: 6,
        title: "Election Campaigns and Strategies",
        category: "politics",
        channel: "Al Jazeera",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "3.5M",
        vidLength: "01:01:25",
        duration: "4 days ago"
    },
    {
        id: 7,
        title: "State Elections 2024: Live Updates",
        category: "politics",
        channel: "ABP News",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "1.2M",
        vidLength: "29:17",
        duration: "2 months ago"
    },
    {
        id: 8,
        title: "Political Trends and Forecasts",
        category: "politics",
        channel: "India Today",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "2.7K",
        vidLength: "36:22",
        duration: "3 weeks ago"
    },
    {
        id: 9,
        title: "Analysis of Election Results",
        category: "politics",
        channel: "The Hindu",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "1.9M",
        vidLength: "01:25:33",
        duration: "2 days ago"
    },
    {
        id: 10,
        title: "Future of Politics in India",
        category: "politics",
        channel: "Times Now",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "3.8M",
        vidLength: "50:55",
        duration: "1 week ago"
    },
    {
        id: 11,
        title: "Political Ideologies and Movements",
        category: "politics",
        channel: "Republic TV",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "2.3M",
        vidLength: "32:44",
        duration: "4 weeks ago"
    },
    {
        id: 12,
        title: "Understanding Political Campaigns",
        category: "politics",
        channel: "The Quint",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "1.5K",
        vidLength: "45:12",
        duration: "2 months ago"
    },
    {
        id: 13,
        title: "Global Political Changes",
        category: "politics",
        channel: "DW News",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "2.1M",
        vidLength: "39:27",
        duration: "5 days ago"
    },
    {
        id: 14,
        title: "Political History and Milestones",
        category: "politics",
        channel: "Rajya Sabha TV",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "3.4M",
        vidLength: "47:31",
        duration: "1 week ago"
    },
    {
        id: 15,
        title: "Election Strategies and Outcomes",
        category: "politics",
        channel: "Bloomberg",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/coBAP70ZN1Y/hqdefault.jpg?sqp=-oaymwEcCOADEI4CSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLCZEPljOs-GsHP_-1TAEfpMVlbiWA",
        vidLink: "",
        views: "2.6M",
        vidLength: "42:15",
        duration: "3 days ago"
    },
    
    // Technology
    {
        id: 16,
        title: "Top 10 Gadgets of 2024",
        category: "technology",
        channel: "TechCrunch",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        vidLink: "",
        views: "3.1M",
        vidLength: "25:45",
        duration: "1 week ago"
    },
    {
        id: 17,
        title: "AI Innovations and Future",
        category: "technology",
        channel: "Tech Insider",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        vidLink: "",
        views: "2.8M",
        vidLength: "01:18:30",
        duration: "2 days ago"
    },
    {
        id: 18,
        title: "The Rise of Quantum Computing",
        category: "technology",
        channel: "Verge Science",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        vidLink: "",
        views: "4.2M",
        vidLength: "22:13",
        duration: "3 days ago"
    },
    {
        id: 19,
        title: "The Future of Autonomous Vehicles",
        category: "technology",
        channel: "CNET",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        vidLink: "",
        views: "1.9M",
        vidLength: "30:47",
        duration: "4 weeks ago"
    },
    {
        id: 20,
        title: "Exploring 5G Technology",
        category: "technology",
        channel: "Engadget",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        vidLink: "",
        views: "3.7M",
        vidLength: "27:12",
        duration: "2 weeks ago"
    },
    {
        id: 21,
        title: "Top Programming Languages in 2024",
        category: "technology",
        channel: "FreeCodeCamp",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        vidLink: "",
        views: "2.3M",
        vidLength: "33:22",
        duration: "5 days ago"
    },
    {
        id: 22,
        title: "Blockchain and Its Applications",
        category: "technology",
        channel: "Crypto Academy",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        vidLink: "",
        views: "1.6M",
        vidLength: "28:39",
        duration: "1 month ago"
    },
    {
        id: 23,
        title: "Advancements in VR and AR",
        category: "technology",
        channel: "VR World",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        vidLink: "",
        views: "2.0M",
        vidLength: "19:54",
        duration: "2 weeks ago"
    },
    {
        id: 24,
        title: "The Impact of AI on Jobs",
        category: "technology",
        channel: "Tech Talks",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        vidLink: "",
        views: "1.7M",
        vidLength: "23:48",
        duration: "3 weeks ago"
    },
    {
        id: 25,
        title: "Cybersecurity in 2024",
        category: "technology",
        channel: "Infosec",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        vidLink: "",
        views: "1.8M",
        vidLength: "24:39",
        duration: "4 days ago"
    },
    {
        id: 26,
        title: "Understanding Machine Learning",
        category: "technology",
        channel: "ML Academy",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        vidLink: "",
        views: "2.4M",
        vidLength: "21:19",
        duration: "1 week ago"
    },
    {
        id: 27,
        title: "The Future of Smart Homes",
        category: "technology",
        channel: "Smart Home",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        vidLink: "",
        views: "2.2M",
        vidLength: "26:54",
        duration: "3 weeks ago"
    },
    {
        id: 28,
        title: "Wearable Tech in 2024",
        category: "technology",
        channel: "Gadget Guru",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        views: "1.9M",
        vidLength: "29:37",
        duration: "2 weeks ago"
    },
    {
        id: 29,
        title: "Space Exploration Technologies",
        category: "technology",
        channel: "SpaceX",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        views: "4.1M",
        vidLength: "34:42",
        duration: "1 day ago"
    },
    {
        id: 30,
        title: "Tech Innovations of the Year",
        category: "technology",
        channel: "Innovate",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/2Cn7lQ_zAgk/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAUYIVzy2fldmEujv5nLhA28tzNsg",
        views: "2.5M",
        vidLength: "28:21",
        duration: "2 months ago"
    },
    
    // Entertainment
        {
            id: 31,
            title: "Top 10 Movies of 2024",
            category: "entertainment",
            channel: "Movie Buff",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "4.5M",
            vidLength: "01:42:15",
            duration: "2 weeks ago"
        },
        {
            id: 32,
            title: "Best TV Shows to Watch",
            category: "entertainment",
            channel: "TV Fanatics",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "3.2M",
            vidLength: "42:15",
            duration: "3 days ago"
        },
        {
            id: 33,
            title: "Top 10 Songs of 2024",
            category: "entertainment",
            channel: "Music Hits",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "5.1M",
            vidLength: "20:37",
            duration: "1 month ago"
        },
        {
            id: 34,
            title: "Celebrity Interviews",
            category: "entertainment",
            channel: "StarTalk",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "2.8M",
            vidLength: "01:42:15",
            duration: "2 weeks ago"
        },
        {
            id: 35,
            title: "The Future of Cinema",
            category: "entertainment",
            channel: "Film Critique",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "3.0M",
            vidLength: "27:14",
            duration: "1 week ago"
        },
        {
            id: 36,
            title: "Top 10 Comedy Shows",
            category: "entertainment",
            channel: "Laugh Out Loud",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "4.2M",
            vidLength: "22:57",
            duration: "3 weeks ago"
        },
        {
            id: 37,
            title: "The Best of Stand-up Comedy",
            category: "entertainment",
            channel: "Comedy Central",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "2.6M",
            vidLength: "19:35",
            duration: "4 days ago"
        },
        {
            id: 38,
            title: "Epic Movie Trailers",
            category: "entertainment",
            channel: "Trailers Galore",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "5.0M",
            vidLength: "15:22",
            duration: "2 months ago"
        },
        {
            id: 39,
            title: "Top Action Movies of 2024",
            category: "entertainment",
            channel: "Action Channel",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "4.8M",
            vidLength: "21:17",
            duration: "6 days ago"
        },
        {
            id: 40,
            title: "Music Festivals to Attend",
            category: "entertainment",
            channel: "Fest Frenzy",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "3.3M",
            vidLength: "25:11",
            duration: "2 weeks ago"
        },
        {
            id: 41,
            title: "Best Animated Movies of 2024",
            category: "entertainment",
            channel: "Animation Hub",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "4.1M",
            vidLength: "19:02",
            duration: "1 month ago"
        },
        {
            id: 42,
            title: "Top 10 Horror Movies of 2024",
            category: "entertainment",
            channel: "Scary Stories",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "5.7M",
            vidLength: "23:18",
            duration: "3 weeks ago"
        },
        {
            id: 43,
            title: "Best Performances of 2024",
            category: "entertainment",
            channel: "Star Performances",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "3.9M",
            vidLength: "28:44",
            duration: "2 days ago"
        },
        {
            id: 44,
            title: "Top 10 Sci-Fi Movies of 2024",
            category: "entertainment",
            channel: "Future Films",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "6.0M",
            vidLength: "30:11",
            duration: "1 week ago"
        },
        {
            id: 45,
            title: "Iconic Moments in Cinema",
            category: "entertainment",
            channel: "Cinephile Dreams",
            chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
            thumbnail: "https://i.ytimg.com/vi/-boPEbe6iaI/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLATR_aaLr17xCYBcR3e7BecNVkK4g",
            vidLink: "",
            views: "3.7M",
            vidLength: "27:53",
            duration: "2 months ago"
        },

    // Education
    {
        id: 46,
        title: "Physics 101: Basics of Motion",
        category: "education",
        channel: "Khan Academy",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "1.2M",
        vidLength: "01:42:15",
        duration: "3 weeks ago"
    },
    {
        id: 47,
        title: "Introduction to Calculus",
        category: "education",
        channel: "MIT OpenCourseWare",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "3.6M",
        vidLength: "42:15",
        duration: "1 month ago"
    },
    {
        id: 48,
        title: "Understanding Quantum Mechanics",
        category: "education",
        channel: "Science Channel",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "2.1M",
        vidLength: "01:42:15",
        duration: "2 days ago"
    },
    {
        id: 49,
        title: "History of Ancient Civilizations",
        category: "education",
        channel: "History Buff",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "2.8M",
        vidLength: "01:42:15",
        duration: "5 days ago"
    },
    {
        id: 50,
        title: "Basic English Grammar",
        category: "education",
        channel: "Learn English",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "1.9M",
        vidLength: "01:42:15",
        duration: "2 weeks ago"
    },
    {
        id: 51,
        title: "Introduction to Computer Science",
        category: "education",
        channel: "CS50",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "4.0M",
        vidLength: "01:42:15",
        duration: "3 weeks ago"
    },
    {
        id: 52,
        title: "Understanding World Economics",
        category: "education",
        channel: "Economics Explained",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "3.5M",
        vidLength: "01:42:15",
        duration: "4 days ago"
    },
    {
        id: 53,
        title: "Chemistry Basics for Beginners",
        category: "education",
        channel: "Chemistry Made Easy",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "2.2M",
        vidLength: "01:42:15",
        duration: "6 days ago"
    },
    {
        id: 54,
        title: "Introduction to Psychology",
        category: "education",
        channel: "Psychology101",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "3.8M",
        vidLength: "42:15",
        duration: "2 months ago"
    },
    {
        id: 55,
        title: "Learning Mathematics: Algebra",
        category: "education",
        channel: "MathGenius",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "2.6M",
        vidLength: "01:42:15",
        duration: "1 week ago"
    },
    {
        id: 56,
        title: "Introduction to Astronomy",
        category: "education",
        channel: "SpaceHub",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "3.0M",
        vidLength: "01:42:15",
        duration: "3 weeks ago"
    },
    {
        id: 57,
        title: "Understanding Geology",
        category: "education",
        channel: "GeoExplorers",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "2.3M",
        vidLength: "01:42:15",
        duration: "4 days ago"
    },
    {
        id: 58,
        title: "Introduction to Art History",
        category: "education",
        channel: "ArtEnthusiast",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "1.7M",
        vidLength: "01:42:15",
        duration: "3 days ago"
    },
    {
        id: 59,
        title: "Introduction to Linguistics",
        category: "education",
        channel: "Linguistic Lingo",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "1.9M",
        vidLength: "01:42:15",
        duration: "2 months ago"
    },
    {
        id: 60,
        title: "The History of Science",
        category: "education",
        channel: "ScienceHistory",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/HbNfCM4ilBQ/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAiNWOUKwOLnaRRWaA7tvBoMdVUsQ",
        vidLink: "",
        views: "2.5M",
        vidLength: "01:42:15",
        duration: "6 days ago"
    },

    // Sports
    {
        id: 61,
        title: "Best Goals of the Season",
        category: "sports",
        channel: "Goal Highlights",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "4.2M",
        vidLength: "15:38",
        duration: "3 weeks ago"
    },
    {
        id: 62,
        title: "NBA Highlights: Best Dunks",
        category: "sports",
        channel: "NBA Recap",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "3.8M",
        vidLength: "12:17",
        duration: "2 days ago"
    },
    {
        id: 63,
        title: "Football: Best Skills and Tricks",
        category: "sports",
        channel: "Football Skills",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "5.6M",
        vidLength: "20:45",
        duration: "1 month ago"
    },
    {
        id: 64,
        title: "Cricket: Top Wickets Compilation",
        category: "sports",
        channel: "Cricket Zone",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "2.3M",
        vidLength: "14:28",
        duration: "2 weeks ago"
    },
    {
        id: 65,
        title: "Tennis: Best Rallies of the Year",
        category: "sports",
        channel: "Tennis World",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "1.9M",
        vidLength: "18:59",
        duration: "5 days ago"
    },
    {
        id: 66,
        title: "Golf: Best Putts of the Season",
        category: "sports",
        channel: "Golf Masters",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "1.1M",
        vidLength: "10:05",
        duration: "4 months ago"
    },
    {
        id: 67,
        title: "Basketball: Best Crossovers",
        category: "sports",
        channel: "Basketball Highlights",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "2.7M",
        vidLength: "22:13",
        duration: "3 days ago"
    },
    {
        id: 68,
        title: "Soccer: Best Free Kicks Compilation",
        category: "sports",
        channel: "Soccer Zone",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "3.4M",
        vidLength: "19:48",
        duration: "1 week ago"
    },
    {
        id: 69,
        title: "Baseball: Top Plays of the Week",
        category: "sports",
        channel: "Baseball Highlights",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "1.5M",
        vidLength: "16:55",
        duration: "6 days ago"
    },
    {
        id: 70,
        title: "Hockey: Best Goals Compilation",
        category: "sports",
        channel: "Hockey Highlights",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "2.8M",
        vidLength: "23:22",
        duration: "2 weeks ago"
    },
    {
        id: 71,
        title: "Cycling: Tour de France Highlights",
        category: "sports",
        channel: "Cycling World",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "3.2M",
        vidLength: "18:49",
        duration: "4 days ago"
    },
    {
        id: 72,
        title: "Athletics: World Championships",
        category: "sports",
        channel: "Athletics World",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "4.7M",
        vidLength: "21:57",
        duration: "2 months ago"
    },
    {
        id: 73,
        title: "Swimming: Olympic Highlights",
        category: "sports",
        channel: "Swimming World",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "3.5M",
        vidLength: "17:28",
        duration: "3 weeks ago"
    },
    {
        id: 74,
        title: "Rugby: Best Tries of the Season",
        category: "sports",
        channel: "Rugby World",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "2.1M",
        vidLength: "14:33",
        duration: "1 day ago"
    },
    {
        id: 75,
        title: "Golf: Masters Tournament Highlights",
        category: "sports",
        channel: "Golf Channel",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/bNLJEsqCFWM/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLBz6Yifk4Yois45IUqryMtmdeE8lg",
        vidLink: "",
        views: "2.3M",
        vidLength: "19:12",
        duration: "6 months ago"
    }
];


const YtShortsData = [
    {
        id: 1,
        title: "Loksabha 2024 Election Result Live",
        channel: "ANI",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "2.5M",
      },
      {
        id: 2,
        title: "Cooking Masterclass: Italian Cuisine",
        channel: "Food Network",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "3.2K",
      },
      {
        id: 3,
        title: "Funny Cat Compilation",
        channel: "Cat Lovers",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "4.7M",
      },
      {
        id: 4,
        title: "Morning Yoga Routine",
        channel: "Yoga with Sara",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "1.8K",
      },
      {
        id: 5,
        title: "Travel Vlog: Exploring Thailand",
        channel: "Wanderlust",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "2.1M",
      },
      {
        id: 6,
        title: "Motivational Speech: Achieve Your Dreams",
        channel: "Inspire Today",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "3.5M",
      },
      {
        id: 7,
        title: "DIY Crafts: How to Make Paper Flowers",
        channel: "Crafty Creations",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "2.9K",
      },
      {
        id: 8,
        title: "Funny Dog Compilation",
        channel: "Dog Lovers",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "4.3M",
      },
      {
        id: 9,
        title: "Fitness Tips: How to Stay Healthy",
        channel: "Fitness Guru",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "3.7K",
      },
      {
        id: 10,
        title: "Hiking Adventures: Exploring the Wilderness",
        channel: "Adventure Seekers",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "2.6M",
      },
      {
        id: 11,
        title: "Exploring Underwater World: Scuba Diving Adventure",
        channel: "Ocean Explorers",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "3.9M",
      },
      {
        id: 12,
        title: "Traveling Solo: Backpacking Across Europe",
        channel: "Solo Traveler",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "2.4K",
      },
      {
        id: 13,
        title: "Cooking Tutorial: How to Make Sushi Rolls",
        channel: "Sushi Chef",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "4.1M",
      },
      {
        id: 14,
        title: "Fashion Haul: Spring Collection 2024",
        channel: "Fashionista",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "1.5K",
      },
      {
        id: 15,
        title: "Tech Review: Latest Smartphone 2024",
        channel: "Tech Guru",
        chLogo: "https://yt3.ggpht.com/3K6h6gpMPf4mK9qh6SXTl0W3PLxnOMzUnFHc2lbS9t-ucS-b4JGcR8nW7ja9XDYkHM-kAnijk2c=s68-c-k-c0x00ffffff-no-rj",
        thumbnail: "https://i.ytimg.com/vi/jTgWNlVW-jg/oardefault.jpg",
        shortsLink: "",
        views: "3.2K",
      }
];

export { YtVideoData, YtShortsData };