import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Component/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NEXT YouTube APP",
  description: "Generated by create next app ..",
};

export default function RootLayout({ children } : { children: React.ReactNode } ) {
  return (
    <html lang="en">
      <body className="bg-[#0f0f0f] text-white">
        <Header />
        {children}
      </body>
    </html>
  );
}
